name: Makefile CI

on:
  push:
jobs:
  build_all:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-16.04
        - ubuntu-18.04
        - macos-latest
        - windows-latest
        compiler:
        - gcc
        - clang

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Make
      run: make CC=${{matrix.compiler}}
